version: '3.7'
services:
  bookservice:
    build: ./src
    image: book_service_api
    container_name: pythonBookServiceAPI
    command: python app.py
    restart: on-failure
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 4001:4000
    networks:
        - default
  mysql:
    image: mysql:5.7
    container_name: MySQLServiceDB
    ports:
        - "3307:3306"
    environment:
        MYSQL_USER: dev
        MYSQL_PASSWORD: 12345678
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_DATABASE: "flaskmysql"
    networks:
      - default
volumes:
  schemas: {}